### ISSUE TITLE
Add documentation and installation information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_heatmap#1]
Please add documentation to the repo including:
* [x] set up info
* [x] screenshot of app
* [x] server requirements
* [x] configuration
* [x] demo service
* [x] open source license info

**Comment by PolBaladas** [comment]
Hi Mario, Can i get Write access please?
Thanks

**Comment by mariobehling** [comment]
Done :-)

**Comment by PolBaladas** [comment]
Thanks!

**Comment by PolBaladas** [comment]
Should we make this the main repo? Instead of pulling from the other one?

**Comment by mariobehling** [comment]
Yes, also good.

**Comment by PolBaladas** [comment]
<img width="1278" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3987198/18433618/f48d8a04-78e8-11e6-836d-85b231aeb5a0.png">

**Comment by PolBaladas** [comment]
Done!

**Comment by mariobehling** [comment]
Good job!

**Comment by PolBaladas** [comment]
Thanks!
